version: '3'
services:
  config-server:
    image: zeromberto/spring-petclinic-config-server:calibration
    networks:
     - net

  discovery-server:
    image: zeromberto/spring-petclinic-discovery-server:calibration
    depends_on:
      - config-server
    entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761
    volumes:
     - /containers/discovery-server:/tmp
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=calibration

  customers-service:
    image: zeromberto/spring-petclinic-customers-service:calibration
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    volumes:
     - /containers/customers-service:/tmp
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=calibration

  visits-service:
    image: zeromberto/spring-petclinic-visits-service:calibration
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    volumes:
     - /containers/visits-service:/tmp
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=calibration

  vets-service:
    image: zeromberto/spring-petclinic-vets-service:calibration
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    volumes:
     - /containers/vets-service:/tmp
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=calibration

  api-gateway:
    image: zeromberto/spring-petclinic-api-gateway:calibration
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080
    volumes:
     - /containers/api-gateway:/tmp
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=calibration

networks:
  net:
