version: '3'
services:
  config-server:
    image: petclinic/spring-petclinic-config-server
    #container_name: config-server
    #ports:
    # - 8888:8888
    volumes:
     - /c/Users/mrombach/tmp/config-server:/tmp
    networks:
     - net

  discovery-server:
    image: petclinic/spring-petclinic-discovery-server
    #container_name: discovery-server
    depends_on:
      - config-server
    entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761
    volumes:
     - /c/Users/mrombach/tmp/discovery-server:/tmp
    networks:
     - net

  customers-service:
    image: petclinic/spring-petclinic-customers-service
    #container_name: customers-service
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    #ports:
    # - 8081:8081
    deploy:
      replicas: 3
      #resources:
      #  limits:
      #    cpus: '0.1'
    volumes:
     - /c/Users/mrombach/tmp/customers-service:/tmp
    networks:
     - net

  visits-service:
    image: petclinic/spring-petclinic-visits-service
    #container_name: visits-service
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    #ports:
    # - 8082:8082
    volumes:
     - /c/Users/mrombach/tmp/visits-service:/tmp
    networks:
     - net

  vets-service:
    image: petclinic/spring-petclinic-vets-service
    #container_name: vets-service
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    #ports:
    # - 8083:8083
    volumes:
     - /c/Users/mrombach/tmp/vets-service:/tmp
    networks:
     - net

  api-gateway:
    image: petclinic/spring-petclinic-api-gateway
    #container_name: api-gateway
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080
    volumes:
     - /c/Users/mrombach/tmp/api-gateway:/tmp
    networks:
     - net

#  tracing-server:
#    image: petclinic/spring-petclinic-tracing-server
#    container_name: tracing-server
#    depends_on:
#     - config-server
#     - discovery-server
#    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
#    ports:
#     - 9411:9411

#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - 80:8080
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - net
      


networks:
  net: