version: '3'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
    image: mysql
    ports:
     - "3306:3306"
     - "33060:33060"
    networks:
     - net
     
networks:
  net:
