version: '2'
services:
  config-server:
    image: zeromberto/spring-petclinic-config-server:eval
    networks:
     - net
    cpuset: '0'
    cpu_quota: 100000
    cpu_shares: 100000
    
  discovery-server:
    image: zeromberto/spring-petclinic-discovery-server:eval
    depends_on:
      - config-server
    entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar2
    cpuset: '1'
    cpu_quota: 100000
    cpu_shares: 100000

  customers-service:
    image: zeromberto/spring-petclinic-customers-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar2
    cpuset: '4'
    cpu_quota: 100000
    cpu_shares: 100000

  visits-service:
    image: zeromberto/spring-petclinic-visits-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar2
    cpuset: '5,6,7'
    cpu_quota: 300000
    cpu_shares: 100000

  vets-service:
    image: zeromberto/spring-petclinic-vets-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar2
    cpuset: '8,9,10'
    cpu_quota: 300000
    cpu_shares: 100000

  api-gateway:
    image: zeromberto/spring-petclinic-api-gateway:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar2
    cpuset: '11,12,13'
    cpu_quota: 300000
    cpu_shares: 100000

networks:
  net:
