version: '3'
services:
  config-server:
    image: zeromberto/spring-petclinic-config-server:eval
    networks:
     - net
    deploy:
      mode: global

  discovery-server:
    image: zeromberto/spring-petclinic-discovery-server:eval
    depends_on:
      - config-server
    entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global

  customers-service0:
    image: zeromberto/spring-petclinic-customers-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 8
        limits:
          cpus: '1.0'
          
  customers-service1:
    image: zeromberto/spring-petclinic-customers-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 9
        limits:
          cpus: '0.66'
          
  customers-service2:
    image: zeromberto/spring-petclinic-customers-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 10
        limits:
          cpus: '0.33'

  visits-service:
    image: zeromberto/spring-petclinic-visits-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 11
        limits:
          cpus: '1.0'

  vets-service:
    image: zeromberto/spring-petclinic-vets-service:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 12
        limits:
          cpus: '1.0'

  api-gateway:
    image: zeromberto/spring-petclinic-api-gateway:eval
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080
    networks:
     - net
    environment:
     - SPRING_PROFILES_ACTIVE=EvalVar3
    deploy:
      mode: global
      resources:
        cpus: 13
        limits:
          cpus: '1.0'

networks:
  net:
